### ISSUE TITLE
Unexpected token '?'

### ISSUE THREAD

**Issue by xeroxstar** [jhurliman/node-rate-limiter#76] opened 2021-05-06 23:17 UTC
I am running this example:
```
import { RateLimiter } from "limiter";

// Allow 150 requests per hour (the Twitter search limit). Also understands
// 'second', 'minute', 'day', or a number of milliseconds
const limiter = new RateLimiter({ tokensPerInterval: 150, interval: "hour" });

async function sendRequest() {
  // This call will throw if we request more than the maximum number of requests
  // that were set in the constructor
  // remainingRequests tells us how many additional requests could be sent
  // right this moment
  const remainingRequests = await limiter.removeTokens(1);
  callMyRequestSendingFunction(...);
}
```

and i am getting this error:

```
this.fireImmediately = fireImmediately ?? false;
                                                ^

SyntaxError: Unexpected token '?'
```

**Comment by jhurliman** [comment] 2021-05-07 01:11
What environment are you running this in?

**Comment by Sir-Will** [comment] 2021-05-07 13:07
Same issue with NodeJS v12.3.1

**Comment by jhurliman** [comment] 2021-05-07 16:53
Thanks. I think the issue is targeting `ES2020` with the TypeScript -> JS compilation, which breaks support for node v12. I'll change the compilation target to `ES2019`.

**Comment by jhurliman** [comment] 2021-05-19 21:35
Fixed in https://github.com/jhurliman/node-rate-limiter/pull/79

**Closed** 2021-05-19 21:37 UTC
